### ISSUE TITLE
My connection page issues

### ISSUE THREAD

**Issue by Stacyyya** [sv-bootcamp/bridgeme-client#125]
1. [android] deactive scroll function on tab menu.
2. Rearrange the "btn_accept" position for each device.
3. Disable the vertical scroll function when user swipe the lists.
4. Delete the grey area when user swipe the lists.
5. Disable btn_accept when user want to delete lists. 
6. delete할 때 바깥영역 누르면 해제되게...!!

**Comment by MechanicKim** [comment]
I will add one more!

When this page is scrollable(This is like that list length is longer than visible area.)
Items of list disappear

**Comment by heartjigi** [comment]
I will add two
1. on new requests 
 if someone sent me new request, then my original list is override by new img
before
![simulator screen shot 2016 12 14 3 09 36](https://cloud.githubusercontent.com/assets/6707284/21171532/f0a94fb6-c20f-11e6-9f14-bb71c435c919.png)
after
![simulator screen shot 2016 12 14 3 09 52](https://cloud.githubusercontent.com/assets/6707284/21171538/f7bd0950-c20f-11e6-8cd3-4210e9ab1d89.png)

2. on new requests 
if delete one, not disappear delete button.
Is it intended?
![simulator screen shot 2016 12 14 3 09 22](https://cloud.githubusercontent.com/assets/6707284/21171601/8094bf5c-c210-11e6-9186-2b3c0e8f3481.png)

**Comment by ifndefdeadmau5** [comment]
@MechanicKim @heartjigi Thank you for bug report! But could you please create another issue for this instead of leaving a comment here? Because if you guys add more and more thing in here, the corresponding pull request will be a huge change...
