### ISSUE TITLE
How come this repository have 50.4% of Makefile rather than Javascript?

### ISSUE THREAD

**Issue by ochanje210** [sv-bootcamp/bridgeme-client#27]

**Comment by ifndefdeadmau5** [comment]
FacebookSDK was included in project..

**Comment by ochanje210** [comment]
was it intended?

**Comment by ifndefdeadmau5** [comment]
I don't think so. We have to get rid of them soon.

**Comment by ochanje210** [comment]
so it was @ace0625's intention that including fbsdk in the remote repo gives you easier setup.
