### ISSUE TITLE
How about using image autoscale in react-native??

### ISSUE THREAD

**Issue by lyw0149** [sv-bootcamp/bridgeme-client#33]
we are using Image like `source={require('../resources/facebook.png_2x')} />` now,
But there is autoscale feature in react-native.
For example, facebook.png
`source={require('../resources/facebook.png')} />`
facebook.png is including all of file below.
|_facebook.png
|_facebook@2x .png
|_facebook@3x.png

for this, we should change all file name
<img width="190" alt="2016-10-28 4 53 57" src="https://cloud.githubusercontent.com/assets/10323205/19799008/301dcda8-9d2f-11e6-8505-db8d8df4c9c5.png">
ex) facebook_2x .png -> facebook@2x .png

**Comment by ifndefdeadmau5** [comment]
Thank you for nice suggestion. We definitely need to apply this

**Comment by ochanje210** [comment]
wow, this is powerful. Thank you
