### ISSUE TITLE
react-native run-android doesn't work

### ISSUE THREAD

**Issue by kayla-kwon** [sv-bootcamp/bridgeme-client#48]
When I ran ```react-native run-android``` , the error below occured.
```
Starting JS server...
Running /Users/KaylaKwon/Library/Android/sdk/platform-tools/adb -s emulator-5554 reverse tcp:8081 tcp:8081
Building and installing the app on the device (cd android && ./gradlew installDebug...
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment.
Go to https://facebook.github.io/react-native/docs/getting-started.html
and check the Android tab for setup instructions.
```

Why I can't run android with this way?

**Comment by ochanje210** [comment]
I guess you need to enable an android emulator or connect a testing device.

**Comment by kayla-kwon** [comment]
When I used a device for the test, it was same.

**Comment by ochanje210** [comment]
you need to set up ip address on your test device

**Comment by ochanje210** [comment]
https://facebook.github.io/react-native/docs/running-on-device-android.html#running-packager-on-a-non-standard-port

**Comment by ochanje210** [comment]
oh never mind. you won't need it for run-android

**Comment by ochanje210** [comment]
try to run: $adb devices
this will show what devices are connected

**Comment by ochanje210** [comment]
if it throws an error saying no devices are connected then, I guess the device is not having USB debugging mode enabled

**Comment by kayla-kwon** [comment]
I've tried that with `android avd` 5 hours ago and checked the available devices.
And it's a USB debugging mode of course. 

I'm using Android Studio for an alternative.

**Comment by ochanje210** [comment]
hm.. try to run $ adb reverse tcp:8081 tcp:8081
