### ISSUE TITLE
[SOLVED][Client] facebook login button customizing problem

### ISSUE THREAD

**Issue by heartjigi** [sv-bootcamp/bridgeme-client#6]
Not able to replace facebook login button with our design.
we try to make image transparent. 
It works on Android but IOS. 

Now, make opacity 0.1 ( if 0, Don't work in IOS). 

like this pic
![image](https://cloud.githubusercontent.com/assets/6707284/18113451/ec29e984-6f6a-11e6-8c48-85656711dbda.png)

We need to find some other way. 
if someone have any idea about this, tell me that plz

**Comment by ethkim** [comment]
Let's not worry too much about how the product would look like exactly. Both facebook and linkedin should have their own plugin button that they provide. Just use that - for now, it doesn't even matter if the 2 buttons don't have the same size :) 

Rendering an additional image on top of another image is a bad idea. What if the original button is slightly smaller than the image on top? Then some part of the larger image around the boundary is not clickable - which is annoying.

**Comment by heartjigi** [comment]
We found way to change login button image with login manager(from FBSDK)
