### ISSUE TITLE
Pictures are crushed.

### ISSUE THREAD

**Issue by MechanicKim** [sv-bootcamp/bridgeme-client#76]
The reason is because of size.
 When local user regist profile picture, our module reduces it's size.
Because of that, we can see a crushed picture. :-(

**Comment by ochanje210** [comment]
are you guys reducing the image from the front-end?

**Comment by SarahhhC** [comment]
Now solved.

**Comment by ochanje210** [comment]
how did u solve it. plz reference any PR# if applicable

**Comment by SarahhhC** [comment]
We moved image resizing feature from front to back. It's in PR#128.
